version: "3.9"
services:
  dev:
    build:
      context: ./
      target: "dev"
    ports:
      - "${DEV_HOST_PORT}:8000"
    volumes:
      - ".:/app:rw"
    command: sh -c "
      npm install &&
      npm run start
      "
  