export enum LoadingString {
  page_index_openDB,
  components_index_loadDocument,
  components_StockList_CustomListItem_deleteItem,
  components_Drawer_Drawer_loadDocument,
  components_Drawer_Drawer_addDocument,
  components_Drawer_EditDocumentArray_EditDocumentArray_save,
  components_Drawer_DocumentItem_deleteDocument,
  components_StockList_StockList_getStockRecords,
  components_StockList_StockList_add,
  components_StockList_EditDialog_update,
  components_StockList_EditDialog_deleteStock,
}