name: Test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm ci
      - run: npm run build
      - run: npm run serve
      - run: npm run start
