name: Test
on:
  push:
    branches: [ test, dev ]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }} # Run for listed os
    steps:
      - uses: actions/checkout@v2 # checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: npm build, serve, start
        run: |
          npm ci
          npm run build
