name: Test
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-lates, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }} # Run for listed os
    steps:
      - uses: actions/checkout@v2 # checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: |
          npm ci
          npm run build
          npm run serve
          npm run start
        env:
          CI: true
